### ISSUE TITLE
CSS Syntax not recognized

### ISSUE THREAD

**Issue by VascularEngineer** [tailwindtoolbox/Admin-Template-Night#1]
Hi I have tried to integrate parts of this template. It seems like github has another version than what's displayed in the demo page: https://www.tailwindtoolbox.com/templates/admin-template-night-demo.php

One example will show the difference: e.g. the "Tasks" menu item has the following classes assigned on the demo page:
class="block py-1 md:py-3 pl-1 align-middle text-<b>gray-500</b> no-underline hover:text-<b>gray-100</b> border-b-2 border-<b>gray-900</b>  hover:border-pink<b>-400</b>"

While on the github page, the source code says:
class="block py-1 md:py-3 pl-1 align-middle text-<b>grey</b> no-underline hover:text-<b>grey-lightest</b> border-b-2 border-black  hover:border-pink<b>-light</b>"

As a result, when you try to use the code from github, it doesn't work as displayed on the demo page. Because my tailwind CSS doesn't recognize the CSS classes used.

**Comment by VascularEngineer** [comment]
Ok I have been asleep I guess. I based my assumptions on the admin-night_v0.html file. If I had used the index.html, the problem wouldn't have been there.

Why is the admin-night_v0.html there anyway? ;) I'll close this issue myself now and move on.

**Comment by tailwindtoolbox** [comment]
Haha, that's how long the template has been there since v0.7!
Good shout though, i'll delete it now!
